### ISSUE TITLE
ssh tunneling

### ISSUE THREAD

**Issue by playmiel** [ewpa/LibSSH-ESP32#21]
as it is not possible to open a tunnel just with the command "ssh -R -N" looking at the I did not understand how to use "ssh_channel_open_forward" so I would like to know if there are examples or video of someone using it?

**Comment by ewpa** [comment]
Does the [upstream documentation ](https://api.libssh.org/stable/libssh_tutor_forwarding.html) answer your question?

**Comment by playmiel** [comment]
when i read the doc i understood that i had to use "ssh_channel_listen_forward()", but i wonder if it is not possible to associate it to another local address?

**Comment by ewpa** [comment]
Please review [this archived thread](https://archive.libssh.org/libssh/2020-04/0000004.html
) all the way through.  It provides a kind-of answer to your question, but not necessarily the one you want.

**Comment by playmiel** [comment]
thanks i finally solved my problem

**Comment by rjjrbatarao** [comment]
@playmiel how did you make it work? do you have sample

**Comment by playmiel** [comment]
hi yes I'll make an example soon
