### ISSUE TITLE
example exec.ino

### ISSUE THREAD

**Issue by defdefred** [ewpa/LibSSH-ESP32#22]
Hello,

https://github.com/ewpa/LibSSH-ESP32/blob/master/examples/exec/exec.ino
"else" missing line 350  or I'm wrong?

I love libssh for ESP32 :-)

**Comment by ewpa** [comment]
I have compared this line to line 176 in the upstream file `examples/authentication.c` and they are the same.  Therefore this code was ported okay.  That is not to say this line is correct or otherwise.  Does it cause any issue?

**Comment by defdefred** [comment]
No, sorry for the shitty issue...
I'm still learning to use libssh and trying to make something usefull with an ESP32 + ssh server.
I'm so glad you port libssh to ESP32!
