### ISSUE TITLE
Ethernet network instead WiFi?

### ISSUE THREAD

**Issue by MarcoCiau** [ewpa/LibSSH-ESP32#34]
I want to use Ethernet instead of WiFi, is this possible, does anyone know what files need to be modified/ported?

**Comment by ewpa** [comment]
It will just work.  You can even use both Ethernet and WiFi concurrently.

**Comment by MarcoCiau** [comment]
Sure. I've tested it by changing the related code about WiFI connection with ETH and it's worked.

Thank you!
