### ISSUE TITLE
RSA private encrypt and public decrypt

### ISSUE THREAD

**Issue by radimkohout** [ewpa/LibSSH-ESP32#4]
Hello,
does this library support encrypting with private RSA key and decrypting with public RSA key? If so, how to do it?
Thanks

**Comment by ewpa** [comment]
This is really a question for upstream.  However I would suggest you consider using the existing mbedtls library on the ESP32 to achieve this, e.g. [How to encrypt and decrypt with RSA - Knowledge Base - Mbed TLS](https://tls.mbed.org/kb/how-to/encrypt-and-decrypt-with-rsa).

**Comment by radimkohout** [comment]
I can't figure out how to do it with mbedTLS.

**Comment by ewpa** [comment]
Where are you having issues?  Have you created a sketch that compiles and runs?  I searched the libssh PKI API and could not find the calls you would need for RSA encryption or decryption, so on the face of it, libssh does not support that functionality.

**Comment by radimkohout** [comment]
The problem is, as you stated, that libssh doesn't support these functions

**Comment by ewpa** [comment]
I can say that the mbed link I provided does do what you need: encrypt and decrypt.  I've used something similar successfully.

**Comment by radimkohout** [comment]
But with reversed keys than normally?

**Comment by ewpa** [comment]
What do you mean?

**Comment by radimkohout** [comment]
Normally you encrypt with public and decrypt with private key. I need to encrypt with private and decrypt with public.

**Comment by ewpa** [comment]
I understand now.  I do not believe that is possible unless you are 'signing'.
